export const copy = {
  searchPlaceholder: "Search groceries",
  allCategories: "All",
  add: "Add",
  removeOne: "Remove one",
  addOne: "Add one",
  basket: "Basket",
  items: "items",
  item: "item",
  minimumReached: "Minimum order reached",
  minimumRemaining: (amount: string) => `Add ₹${amount} more to reach the minimum`,
  emptySearch: "No products match your search.",
  openBasket: "View basket",
  deliveryArea: "Neighbourhood delivery",
  checkout: "Checkout", close: "Close", orderPlaced: "Order placed", orderCode: "Your order code",
  keepCode: "Keep this code to check your order status.", checkStatus: "Check order status",
  name: "Name", mobile: "Mobile number", phoneHint: "10-digit Indian mobile",
  fulfilmentQuestion: "How would you like it?", delivery: "Delivery", pickup: "Pickup",
  address: "Delivery address", payment: "Payment on delivery", cash: "Cash", upi: "UPI",
  notes: "Anything else? (optional)", placeOrder: "Place order", placingOrder: "Placing order…",
  free: "Free", total: "Total",
  repeatTitle: "Order the same as last time",
  repeatPrompt: "Enter your mobile number to see your last order",
  repeatCheck: "Check", repeatChecking: "Checking…",
  repeatNotFound: "No previous order found for this number.",
  repeatBasedOn: (code: string, date: string) => `Based on order #${code} from ${date}`,
  repeatUnavailable: "no longer available",
  repeatPriceChanged: (was: string, now: string) => `price changed: was ₹${was}, now ₹${now}`,
  repeatAddAll: "Add these to my basket",
  repeatAdded: "Added to your basket below.",
  agreeToTermsPrefix: "I agree to the", termsWord: "Terms", privacyWord: "Privacy Policy",
  agreeRequired: "Please agree to the Terms and Privacy Policy to place this order.",
} as const;

export const statusCopy = {
  back: "Back to shop",
  title: "Check order status",
  instructions: "Enter your order code and mobile number.",
  code: "Order code",
  mobile: "Mobile number",
  submit: "Check status",
  notFound: "No matching order found.",
  order: "Order",
  method: "Method",
  total: "Total",
};
